language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - vendor
    - laminas-mkdoc-theme

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - COVERAGE_DEPS="satooshi/php-coveralls"
    - LEGACY_DEPS="phpunit/phpunit"
    - SITE_URL=https://docs.laminas.dev/laminas-component-installer
    - GH_USER_NAME="Matthew Weier O'Phinney"
    - GH_USER_EMAIL=matthew@weierophinney.net
    - GH_REF=github.com/laminas/laminas-component-installer.git
    - secure: "moDyn4E7j7f2KhiRJK8z5Ps3tJ9EB37MBLQq78NJqmPBRttiCG5PQ2ru62MCQhXKPncjDVd6d9TwA3DRryF49mLqLOYHwYuFM6sgdtRbHi9d5X8jxorsABqFI3d9Wu/A8+vwbmjpw5MPKH96k7n5IaDSCsmsd8jX95gdztybOx+BZ5PY1paJyfwydTo320s9ev0g6yTHlG9LYHhtmPyrog/4Vxsm2yUcEOFLQjY2EwLNTlqQJ3c5LrOaELsZZHwpPTItjX5iQgOs/A3XYsbZHjzFcY4m9wnHryhhTAD5QKyu1kf+XewLaminasNn+7ROCKGXOJoYb9+mOEL7p3vrQQK9Y16GN2IXn7mAHBJpAefl3aaJFyhf17eyXwDDSCFIBvSZsLLaminasm/lyJQXhwCuT49sdDDGz3uR5IZ8Zl4n0eiiR7s9QvxNV288zJs7BiWAyU7bRoXe3zkraKbmiqz5LW6ko1Qm3oUzZsRp7oSjzuLg+jO8CccGIY/jhOSaj24tw9aIw8iYNV9/QzR/ncHi/i3v6fOYX+tjoF8Fao9RrBMRkKCywTrm9F9eOO6rDUSHj43eXvQ7awQXoK5DZTwUGwCFkj+2f1FfQw23m8e6dTS4eLdmb2PWQuD28Q/x5+HeAo9TXSJTBsXEGeSTbW/35lMbbtq36eo+3OJnVcQFHNeg3+34U="

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - DEPS=lowest
    - php: 5.6
      env:
        - DEPS=latest
        - TEST_COVERAGE=true
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
    - php: 7
      env:
        - DEPS=lowest
    - php: 7
      env:
        - DEPS=latest
        - CS_CHECK=true
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=latest
    - php: hhvm
      env:
        - DEPS=lowest
    - php: hhvm
      env:
        - DEPS=locked
    - php: hhvm
      env:
        - DEPS=latest
  allow_failures:
    - php: hhvm

before_install:
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" && $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini ; fi
  - travis_retry composer self-update

install:
  - travis_retry composer install $COMPOSER_ARGS --ignore-platform-reqs
  - if [[ $TRAVIS_PHP_VERSION =~ ^5.6 ]]; then travis_retry composer update $COMPOSER_ARGS --with-dependencies $LEGACY_DEPS ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS $COVERAGE_DEPS ; fi
  - composer show

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer license-check ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then travis_retry curl -sSL https://raw.githubusercontent.com/laminas/laminas-mkdoc-theme/master/theme-installer.sh | bash ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer upload-coverage ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; ./laminas-mkdoc-theme/deploy.sh ; echo "Completed deploying documentation" ; fi

notifications:
  email: false
    channels:
      - "irc.freenode.org#laminastalk.dev"
    on_success: change
    on_failure: always
  slack:
    rooms:
      - secure: "bmaMU0Uz8yLADIZjZp1/2RRICjOo0WfjFiVxUyNCmaYDMaNTK78dTprzoPeh6ol73apR7FCXJDeUbA7nk9xXao/BWOPFEi0NxrEVTh8Fh1MVMXY8aP0+DdtBAaoW9wKulOjzV8LeE533cFSsWLIE5qOm8B6H48VWnAHZTsn0j9jmjTWsY8L1G26TnF2JzRZiyqbPZP+GI/3VZngEuv077xTXuf1mAnHzdtZdCfw9+aWiBrlEgMh8ZPyg6S5E0jh2XYttLPD+dSXPljBC85SWqMw7QM7WIrU4iGAUUdMYD6gZoUPkwFcCbms96FX3nkX5TdY11FepA47aZY4dE/GvJXaspXhpDcTHkvovZoSvTz4F3pAgheEqDFV1L8jJfDley36uln9EvuEP8EBG1K9p0OrjfW0ss5tJxaKNZ/8Dx3ghteOU2ONK/KFM8ecZHvJ/DsoMqF+SOrDVA7ICEoSYpTK8vqwZI2iD9xkfLCtDRHj7k3bHZq2g7t+iX/zxhlaminasi/LR+x84W+VkmeHM7JwtSyc/vyfZV1gnohnuyRvWLaminashkRfryByDwuBYkpavrpFhamayCireSie8aGqq9UN8C58tBOFT6rf7ihn1PVBHz/IxmAH533hdTB/GBWFl8pd+xfNdDBnl8av/QxfjV0fRr+aX3jM7Jfpu/CD0z9geuetKs="
    on_success: change
    on_failure: always
