docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
site_name: laminas-component-installer
site_description: Laminas\Component\Installer
repo_url: 'https://github.com/laminas/laminas-component-installer'
